<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V8TS46C" failures="1" tests="3" name="mytest" time="0.164" errors="0" timestamp="2023-08-16T22:55:41 IST">
  <testcase classname="day36.Test1" name="test1" time="0.036">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at day36.Test1.test1(Test1.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="day36.Test1" name="test2" time="0.01"/>
  <testcase classname="day36.Test1" name="test3" time="0.002"/>
</testsuite> <!-- mytest -->
